language: python
python:
  - "3.7"
  - "nightly"
install:
  - pip install -e .
  - pip install coverage
  - pip install mypy
  - pip install sqlalchemy-stubs
  - pip install pycodestyle
  - pip install pylint
script: ./test.sh
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  skip_existing: true
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
